name: Super-Linter

on: push

jobs:
  super-linter:
    name: Lint Code Base
    runs-on: ubuntu-latest
    steps:
      name: Checkout Code
      uses: actions/checkout@v2
      
      name: Run Super Lint
      uses: github/superlinter@v3
      
      env:
        DEFAULT_BRANCH: main
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
